AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
